AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 371417955885

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: mart256
      AccountId: '371417955885'
      RootEmail: mart256@gmail.com
      Alias: codigo-morsa

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      Accounts: !Ref DemoTeamAccount

  DemoTeamAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: demo-team
      AccountId: '167037961755'
      RootEmail: electro.teachings@gmail.com
      Alias: codigo-morsa-dev-1


